### PR TITLE
fixed camera confiner

### PR DESCRIPTION
**Pull request by farskw0w**
CinemachineConfiner's bounding collider was weirdly shaped not allowing the camera to move too far up or down. Fixed now. Green outline is the collider for the confiner.
image

### CODE REVIEW

**Comment by CharmedSatyr** [comment]
@farskw0w Maybe this is too big now? I had a lot of empty space to explore when I was trying to figure out what this PR did and ended up hitting some sky mountains. I don't think I have to interact with the level now to get to the little house. Maybe it would help if we knew your future plans for level design.

**Comment by farskw0w** [comment]
The sky mountain things were just meant to be something to contain the player, but yeah I think they're probably too far up and you can just float over everything. I'll lower it for now and maybe later I can add some things around the top ends of the level to make the space feel like it could be underwater and not just a normal platformer where you stay on the ground most of the time.

Between alpha and beta builds, I'd like to extend the level and add more to it because it's really short right now and wouldn't take more than 2 minutes to get through it and it's kind of boring.

**Comment by farskw0w** [comment]
image
Lowered mountain things and adjusted CinemachineConfiner to fit with the new height of the level. The player can't float over everything without seeing the hill in the middle. There isn't as much empty space anymore.

**Review by CharmedSatyr — APPROVED** [review]
I'll approve and look forward to maybe making the top of the *water* the uppermost boundary later, with lots to do beneath the waves.

**Comment by farskw0w** [comment]
renaming NewLevel --> Seamount didn't work

**Comment by farskw0w** [comment]
Closed, re-made branch and new PR to replace this one. Already approved and merged into main.

**Pull request closed without merging**
