### PR TITLE
Zach-MovementChanges-base

### PR DESCRIPTION
**Pull request by MarZ4c**
Movement Changes that fix a lot of bugs such as player getting stuck in walls.

### CODE REVIEW

**Comment by farskw0w** [comment]
There's something odd going on with sideways movement. Whenever I move strictly up/down it also moves me diagonally sideways in whichever direction I was moving last.

Like if I move a few steps to the right then stop and wait for my character to fully stop moving, then hold W to go straight up, he'll go diagonally up and to the right.

**Comment by MarZ4c** [comment]
Working on a fix.

**Comment by farskw0w** [comment]
works on sample scene, but now the player can't move on NewLevel. I enabled the playercontroller.cs script but he still doesn't move

**Comment by farskw0w** [comment]
movement works in NewLevel now

**Comment by CharmedSatyr** [comment]
@MarZ4c I rebased your branch on main. Can you list out all the things this is expected to do?
I'm seeing:
- My player is very fast now, maybe too fast.
- Gravity is very weak, which is good.
- Blobs do not disappear when killed, they stay there bouncing but cannot be collided with.
- I haven't been able to get stuck in a wall.

**Comment by MarZ4c** [comment]
The main intention was to get the PlayerController script to act like the now deleted PlayerMovement Script. I also increased the movement speed because the player felt too sluggish in the alpha and did not feel like a shark swimming though water. We can discuss this more with the rest of the team if we want to keep a slower feel to the game or increase its speed.

1. Intended

2.Intended

3.Fixed. Enemies can now die again.

4. Thank God

**Review by farskw0w — APPROVED** [review]

**Pull request merged**
