### PR TITLE
Joseph sound updates 1

### PR DESCRIPTION
**Pull request by CharmedSatyr**
This adds the following sound integrations to Seamount (everything Deni has posted so far):
- New background music
- Movement FX triggered by player input
- Death and Hurt sound effects
- Collectible sound effects when the player eats a former token
- A Win sound effect when the player enters the Victory Zone

### CODE REVIEW

**Comment by MarZ4c** [comment]
All sounds you mentioned seem to be working.

Everytime I press a movement key the movement sound plays and they layer on top of each other sometimes being very loud.

This is a minor bug so not a top priority.

**Comment by CharmedSatyr** [comment]
> 

I guess I haven't noticed that. They've seemed to blend together in a way that sounded natural, at least with the music on. I can add some checks so they don't layer.

**Comment by CharmedSatyr** [comment]
> > 
> 
> I guess I haven't noticed that. They've seemed to blend together in a way that sounded natural, at least with the music on. I can add some checks so they don't layer.

Actually, I am not even able to get the sounds to layer locally. If I log each time the sound is played, the logs are spaced out reasonably. Do you have any additional repro steps or blockers for this PR?

**Comment by MarZ4c** [comment]
I am pressing multiple different directions at, or close to, the same time. If its not happening on your machine we can get someone else to test it to see if it happens on their computer. Again it's minor bug.

**Comment by CharmedSatyr** [comment]
> I am pressing multiple different directions at, or close to, the same time. If its not happening on your machine we can get someone else to test it to see if it happens on their computer. Again it's minor bug.

@MarZ4c I pushed up a change to check if the audio source is already playing before triggering it again. Does that fix your issue?

**Review by MarZ4c — APPROVED** [review]
I think that fixed it.

**Pull request merged**
