### PR TITLE
Add Back to Main Menu button to Victory scene.

### PR DESCRIPTION
**Pull request by CharmedSatyr**
In the Victory scene that shows your final score, you should now see a "Back to Main Menu" button. Clicking it should take you back to the Title scene. The Title scene (and everything else) should still work as expected.

### CODE REVIEW

**Comment by MarZ4c** [comment]
-victory screen "back to menu button" does work as intended.

-loading level after going back to the main menu causes the game to crash whenever the player interacts with an object

Error code:
MissingReferenceException: The object of type 'PlayerController' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Component.GetComponent[T] () (at <a1efe86478034c12aa24d00c7dc715fe>:0)
Platformer.Gameplay.PlayerAte.Execute () (at Assets/Scripts/Gameplay/PlayerAte.cs:32)

**Comment by CharmedSatyr** [comment]
> -victory screen "back to menu button" does work as intended.
> 
> -loading level after going back to the main menu causes the game to crash whenever the player interacts with an object
> 
> Error code: MissingReferenceException: The object of type 'PlayerController' has been destroyed but you are still trying to access it. Your script should either check if it is null or you should not destroy the object. UnityEngine.Component.GetComponent[T] () (at :0) Platformer.Gameplay.PlayerAte.Execute () (at Assets/Scripts/Gameplay/PlayerAte.cs:32)

Good catch, this repros locally for me as well.

**Comment by CharmedSatyr** [comment]
> 

Also definitely not due to my changes here. I wonder if there's anything else that doesn't get reset properly after the level ends the first time.

**Comment by CharmedSatyr** [comment]
@MarZ4c This one should be fixed.

**Review by MarZ4c — APPROVED** [review]
Looks good.

**Pull request merged**
