### PR TITLE
Campbellzach hazards destructibles

### PR DESCRIPTION
**Pull request by farskw0w**
- Added an ending section that can be destroyed if you're big enough, scale required set to 3 for now 
- Added a few enemies in the new section
- Added a large crab at the end
- Added a few small hazards to avoid/destroy at the end depending on how big the player is
- Adjusted camera collider slightly to fit with the new section
- All breakable objects are white to indicate they can be destroyed, hazards are red

### CODE REVIEW

**Comment by CharmedSatyr** [comment]
Why the need for a new PR? Is this very different from the last one?

Notes:
- BLOCKER: The music is toggled off and some sounds are missing. That shouldn't be the case in our main branch. Conflict resolution issues?
- Love that we finally have some breakable walls in. I cut a ticket to make destroying them make a good sound. It looks like there are some hazards, too, but by the time I get to them I'm always too big for them to matter.
- Love the moving enemies. I think we could add more big ones and make the world feel more dangerous toward the beginning of the level.
- There's still a lot of empty space to fill. It's easy to find paths with no enemies or hazards.
- The end boss is boxed away and very optional. What if it was moving up and down and offering a spirited defense? What about a giant squid rather than crab?
- I'm struggling to understand tiny mode. I can't have eaten anything if I want to squeeze into the middle shelf toward the beginning of the level. Then, when I get into the bowl of the volcano, if I eat everything inside, I'm still not big enough to break through the walls, but I'm too big to go back the way I came. I'm stuck. Maybe the end of the level is more interesting while tiny, but I don't feel incentivized to avoid eating everything I see. If tiny mode is to be a thing, there should be some tickets to fix that - maybe points only tiny players can get, communicated early and on the scoreboard so they have a chance at a high score.

I think the only blocker for me approving this is making sure the music isn't accidentally zoinked out. We can continue to work on other stuff in later branches. Please cut tickets for further iterations you have in mind.

**Comment by farskw0w** [comment]
The old PR closed automatically when I rebased from main, not sure why.

- Music turned back on, we had a few conflicts when rebasing involving audio. Probably got disabled then.
- The walls inside the volcano were meant to be breakable if you ate all the fish inside, fixed now.
- Giant squid sounds good.
- We could use the empty area above the spawn to make some tiny-only spaces that have a lot of fish in them.

Side note:
Zach and I noticed something weird going on with the collision of the crabs. It's probably because they were based on the slimeball dudes from the template. Their collision is expanding and retracting upwards, likely because the slimes were jumping in samplescene. Just wanted to mention it so I don't forget.

**Comment by CharmedSatyr** [comment]
> The old PR closed automatically when I rebased from main, not sure why.
> 
>     * Music turned back on, we had a few conflicts when rebasing involving audio. Probably got disabled then.
> 
>     * The walls inside the volcano were meant to be breakable if you ate all the fish inside, fixed now.
> 
>     * Giant squid sounds good.
> 
>     * We could use the empty area above the spawn to make some tiny-only spaces that have a lot of fish in them.
> 
> 
> Side note: Zach and I noticed something weird going on with the collision of the crabs. It's probably because they were based on the slimeball dudes from the template. Their collision is expanding and retracting upwards, likely because the slimes were jumping in samplescene. Just wanted to mention it so I don't forget.

@farskw0w Sounds like we need a ticket!

**Review by CharmedSatyr — APPROVED** [review]
Initial changes look good! Let's make sure we have follow-up tickets in for any further iteration we want to do.

**Comment by CharmedSatyr** [comment]
> Initial changes look good! Let's make sure we have follow-up tickets in for any further iteration we want to do.

I tried again and noticed that the win sound was missing when the player reaches the totem, so I added it back in this branch.

**Pull request merged**
