### PR TITLE
Hazards and breakable walls zach brach 7/31

### PR DESCRIPTION
**Pull request by MarZ4c**

### CODE REVIEW

**Comment by CharmedSatyr** [comment]
I merged my PRs and rebased your branch from main. No conflicts.

**Comment by CharmedSatyr** [comment]
> _ No description provided. _

Could you put testing instructions on your PRs so we know we're hitting all the beats?

**Comment by CharmedSatyr** [comment]
General notes: You seem to have carried over code from your last PR without addressing all my comments. Did you want to close your old branch? Also, it's better to have small separate branches for individual features you're trying to add. One branch for movement changes, one for breakable objects, one for hazards. That way we can review them more quickly and understand exactly what changes are trying to contribute to each new feature.

Playtest notes:
1) The player moves very fast now, too fast to feel aquatic.
2) The player gets stuck in walls a lot now.
3) The big red block appears to be a hazard and kills me. Good!
4) The big white block doesn't really respond to me. Maybe it's intended to be breakable once the player is at a certain size?

**Comment by MarZ4c** [comment]
1.That can be adjusted in the player inspector had it high to move around the scene faster. 4 max speed and 3 drift speed felt good to me.

2. I can put up a bug tab on trello and start seeing if I can fix that.

3.I should mention that I have it set so if a player reaches a certain size the red block will be destroyed but if we don't want that hazard to be destroyed we can set the destruction size to an impossible to reach number in the inspector.

4.Yes the white block is destroyed once the player reaches 1.5 in size. also adjustable in the inspector.

Sorry about the big list of changes and no notes still learning the proper etiquette of GitHub.
 also yes closing the old PR would be good. I'm not sure what other issues you're referring to from the previous PR unless you were just talking about the faster movement speed.

**Comment by CharmedSatyr** [comment]
> 1.That can be adjusted in the player inspector had it high to move around the scene faster. 4 max speed and 3 drift speed felt good to me.
> 
>     2. I can put up a bug tab on trello and start seeing if I can fix that.
> 
> 
> 3.I should mention that I have it set so if a player reaches a certain size the red block will be destroyed but if we don't want that hazard to be destroyed we can set the destruction size to an impossible to reach number in the inspector.
> 
> 4.Yes the white block is destroyed once the player reaches 1.5 in size. also adjustable in the inspector.
> 
> Sorry about the big list of changes and no notes still learning the proper etiquette of GitHub. also yes closing the old PR would be good. I'm not sure what other issues you're referring to from the previous PR unless you were just talking about the faster movement speed.

1. Please back out those changes from this branch. You should avoid pushing up local test values. The only code we want to merge to main is what should make it into the final project. We should be able to make a production build for itch.io from the main branch, not say, "Oh, it'll work right if you tweak this and that first" in an undocumented fashion.
2. I'm kinda nervous about introducing that problem to main until we know what the deal is. Can you try to troubleshoot now?
3. Roger. Maybe a separate issue - are the red blocks going to replace the red blobs? I'm actually finding now that the red blobs start dying when I jump on them after I get big enough. It doesn't happen on main.
4. The white block does disappear when the player gets big enough! Neat!

**Comment by MarZ4c** [comment]
So I looked into the bug and I know what's causing it but don't know how to fix it. 

The players rigid body is getting stuck inside the tiles. Very common when the player grows in size near a wall. The player can also get stuck inside while moving in a y and x direction towards a wall and then tapping the reverse direction while in collision with the wall, happens less frequently but enough to be noticeable.

I think the best fix would be to detect when the player enters a tile and then push them out of it but I have no idea how to program that.

Also no the red blocks will not replace enemies. I figured red blocks would be for destructible hazards like spikes or something while keeping the blobs as moving enemies like jellyfish or floating mines that bob up and down.

**Comment by CharmedSatyr** [comment]
> So I looked into the bug and I know what's causing it but don't know how to fix it.
> 
> The players rigid body is getting stuck inside the tiles. Very common when the player grows in size near a wall. The player can also get stuck inside while moving in a y and x direction towards a wall and then tapping the reverse direction while in collision with the wall, happens less frequently but enough to be noticeable.
> 
> I think the best fix would be to detect when the player enters a tile and then push them out of it but I have no idea how to program that.
> 
> Also no the red blocks will not replace enemies. I figured red blocks would be for destructible hazards like spikes or something while keeping the blobs as moving enemies like jellyfish or floating mines that bob up and down.

I suspect there's still something from the Movement Changes branch that's interacting with your new blocks. I would recommend the following. 

1. Close Movement Changes and this branch.
2. Go to the `main` branch and create a new branch based on it that uses the `zach-hazards-base` syntax, so everybody can more easily see which PRs are yours. Add the changes you need that are only related to hazards to it. You can reuse whatever you need from this branch.
3. Do the same for destructible objects - `zach-destructibles-base`.
4. Put up 2 new PRs for the two branches.

We definitely don't want to get in a situation where `main` is buggy, and we don't know why or how to fix it. So the two branches should be as small and functional and well-tested as possible, so it's easier for everybody to be confident moving forward.

**Pull request closed without merging**
