### PR TITLE
Zach-DestrtiblesChangeColor-Base

### PR DESCRIPTION
**Pull request by MarZ4c**
Blocks will now change to magenta when breakable. Also changed the sprites of destructible walls and hazards.

### CODE REVIEW

**Comment by farskw0w** [comment]
image
Looks good, the red hazards are kind of dark and a little hard to see. Can they be made a brighter red?

**Comment by MarZ4c** [comment]
Not by much

**Comment by farskw0w** [comment]
That's a lot better but they're still a little hard to see when the destructible walls change to purple and don't really scream "danger". Also, I think one of the prefabs didn't get its collision updated.
image

**Comment by MarZ4c** [comment]
Updated the colliders on the destructible's.

**Comment by farskw0w** [comment]
they all look good now, approved.

**Review by farskw0w — APPROVED** [review]

**Pull request merged**
